mvault:
  tag: sha-76576
  region: us-east-1
hpp:
  tag: tga-asas
  region: us-west-2
mesb:
  tag: sha-6565
  region: ap-south-1
mpoint:
  tag: sha-hgnbhvv12
  region: eu-central-1
mretail:
  tag: sha-hhhhjjj
  region: ap-northeast-1
vision:
  tag: sha-9799
  region: ap-northeast-1
bre:
  tag: sha-jhgmm
  region: ap-northeast-1
dwh:
  tag: sha-tytujj
  region: ap-northeast-1
env:
  REQUEST_LOG_LEVEL: INFO
  DEPLOYMENT_ENV: production
