mvault:
  tag: sha-76576
  region: us-east-1
hpp:
  tag: sha-98799
  region: us-west-2
mesb:
  tag: sha-35456
  region: ap-south-1
mpoint:
  tag: sha-11111
  region: eu-central-1
mretail:
  tag: sha-jhgkk
  region: ap-northeast-1
vision:
  tag: sha-7899
  region: ap-northeast-1
bre:
  tag: sha-hjkkkk
  region: ap-northeast-1
dwh:
  tag: sha-22222
  region: ap-northeast-1
env:
  REQUEST_LOG_LEVEL: INFO
  DEPLOYMENT_ENV: production
